Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 75, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 38, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.
Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 75, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 38, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.
Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 75, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 34, in top-level template code
    <span class="like-count" id="like-count-{{ image }}">{{ image_likes.get(image, 0) }}</span>
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'image_likes' is undefined
Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 75, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 34, in top-level template code
    <span class="like-count" id="like-count-{{ image }}">{{ image_likes.get(image, 0) }}</span>
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'image_likes' is undefined
Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 75, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 34, in top-level template code
    <span class="like-count" id="like-count-{{ image }}">{{ image_likes.get(image, 0) }}</span>
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'image_likes' is undefined
Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 79, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 34, in top-level template code
    <span class="like-count" id="like-count-{{ image }}">{{ image_likes.get(image, 0) }}</span>
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'image_likes' is undefined
Exception on /choose_city/上海 [GET]
Traceback (most recent call last):
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/app.py", line 80, in city_gallery
    return render_template('gallery.html', city=city, images=images)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hzh/Library/Mobile Documents/com~apple~CloudDocs/程序/网页设计/templates/gallery.html", line 34, in top-level template code
    <span class="like-count" id="like-count-{{ image }}">{{ image_likes.get(image, 0) }}</span>
  File "/Users/hzh/miniforge3/envs/tfpy39/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'image_likes' is undefined
